"""add center_id to users

Revision ID: 6bfafca3f353
Revises: e493d3520edc
Create Date: 2026-07-08 00:51:59.182146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfafca3f353'
down_revision: Union[str, Sequence[str], None] = 'e493d3520edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('center_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'centers', ['center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'center_id')
    # ### end Alembic commands ###
